In [1]:
import numpy as np
import pandas as pd

# from sudo_solo import creat_table,change_num_list,input_table

## 1.0建立棋盘

In [2]:
sudoku_df=pd.DataFrame()

In [3]:
row_list=[]
for i in range(1,10):
    row_list+=range(1,10)
row_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

In [4]:
col_list=[]
for i in range(1,10):
    col_list+=[i,i,i,i,i,i,i,i,i]

In [5]:
#录入row_num,col_num信息
sudoku_df['row_num']=row_list
sudoku_df['col_num']=col_list

In [6]:
nums_ls='123456789'
sudoku_df['num_list']=nums_ls
sudoku_df['num_real']=0

In [7]:
#录入group——key信息
group_keys=['a','a','a','b','b','b','c','c','c',
            'a','a','a','b','b','b','c','c','c',
            'a','a','a','b','b','b','c','c','c',
            'd','d','d','e','e','e','f','f','f',
            'd','d','d','e','e','e','f','f','f',
            'd','d','d','e','e','e','f','f','f',
            'g','g','g','h','h','h','i','i','i',
            'g','g','g','h','h','h','i','i','i',
            'g','g','g','h','h','h','i','i','i',
]
sudoku_df['group_key']=group_keys

In [8]:
sudoku_df

    row_num  col_num   num_list  num_real group_key
0         1        1  123456789         0         a
1         2        1  123456789         0         a
2         3        1  123456789         0         a
3         4        1  123456789         0         b
4         5        1  123456789         0         b
..      ...      ...        ...       ...       ...
76        5        9  123456789         0         h
77        6        9  123456789         0         h
78        7        9  123456789         0         i
79        8        9  123456789         0         i
80        9        9  123456789         0         i

[81 rows x 5 columns]

## 2.0棋盘录入开局信息

In [9]:
# 根据已经确定的blog更新相关row、col、group信息

def update_associated_blog(index_num,num):
    #检查每一row/col/group
    row_num=sudoku_df.loc[index_num,'row_num']
    col_num=sudoku_df.loc[index_num,'col_num']
    group_key=sudoku_df.loc[index_num,'group_key']
    index_list=sudoku_df[(sudoku_df['row_num']==row_num)|
                         (sudoku_df['col_num']==col_num)|
                         (sudoku_df['group_key']==group_key)].index
    index_list=index_list.tolist()
    print('后续将更新blog的index为：')
    print(str(index_list))
    
    #检查详细的每个区块
    for blog_index in index_list:
#         print('检查index:'+str(blog_index))
      
        blog_num_list=sudoku_df.loc[blog_index,'num_list']
       
#         print('num_list 为：'+str(blog_num_list))
     
        #判断blog——list是否为int
        if len(blog_num_list)==1:
            print('pass')
            
        else:
            if str(num) in blog_num_list:
                sudoku_df.loc[blog_index,'num_list']=blog_num_list.replace(str(num),'')
        print('-'*10)

In [10]:
# 将信息录入到棋盘df中
def input_blog(row,col,num):
    index_num=sudoku_df[(sudoku_df['row_num']==row)&(sudoku_df['col_num']==col)].index    
    sudoku_df.loc[index_num,'num_real']=num
    sudoku_df.loc[index_num,'num_list']=str(num)    
    print(sudoku_df.loc[index_num])

In [11]:
# 数独数据初始值
start_nums=[
    1,2,8,
    1,6,7,
    1,9,6,
    2,2,3,
    2,3,9,
    2,4,2,
    2,6,8,
    3,1,4,
    3,4,1,
    3,5,3,
    4,1,9,
    4,3,5,
    4,9,4,
    5,3,3,
    6,1,6,
    6,2,2,
    6,6,5,
    7,1,8,
    7,3,1,
    7,6,6,
    7,7,2,
    8,4,5,
    9,2,6,
    9,4,3,
    9,7,8   
    
]

In [12]:
# 将初始值start_nums 录入sudo——df
st_num=0
while st_num<len(start_nums):
    input_blog(start_nums[st_num],start_nums[st_num+1],start_nums[st_num+2])
    st_num+=3

   row_num  col_num num_list  num_real group_key
9        1        2        8         8         a
    row_num  col_num num_list  num_real group_key
45        1        6        7         7         d
    row_num  col_num num_list  num_real group_key
72        1        9        6         6         g
    row_num  col_num num_list  num_real group_key
10        2        2        3         3         a
    row_num  col_num num_list  num_real group_key
19        2        3        9         9         a
    row_num  col_num num_list  num_real group_key
28        2        4        2         2         d
    row_num  col_num num_list  num_real group_key
46        2        6        8         8         d
   row_num  col_num num_list  num_real group_key
2        3        1        4         4         a
    row_num  col_num num_list  num_real group_key
29        3        4        1         1         d
    row_num  col_num num_list  num_real group_key
38        3        5        3         3         d
   row_num  col_num num_list  num_real group_key
3        4        1        9         9         b
    row_num  col_num num_list  num_real group_key
21        4        3        5         5         b
    row_num  col_num num_list  num_real group_key
75        4        9        4         4         h
    row_num  col_num num_list  num_real group_key
22        5        3        3         3         b
   row_num  col_num num_list  num_real group_key
5        6        1        6         6         b
    row_num  col_num num_list  num_real group_key
14        6        2        2         2         b
    row_num  col_num num_list  num_real group_key
50        6        6        5         5         e
   row_num  col_num num_list  num_real group_key
6        7        1        8         8         c
    row_num  col_num num_list  num_real group_key
24        7        3        1         1         c
    row_num  col_num num_list  num_real group_key
51        7        6        6         6         f
    row_num  col_num num_list  num_real group_key
60        7        7        2         2         i
    row_num  col_num num_list  num_real group_key
34        8        4        5         5         f
    row_num  col_num num_list  num_real group_key
17        9        2        6         6         c
    row_num  col_num num_list  num_real group_key
35        9        4        3         3         f
    row_num  col_num num_list  num_real group_key
62        9        7        8         8         i

In [13]:
sudoku_df

    row_num  col_num   num_list  num_real group_key
0         1        1  123456789         0         a
1         2        1  123456789         0         a
2         3        1          4         4         a
3         4        1          9         9         b
4         5        1  123456789         0         b
..      ...      ...        ...       ...       ...
76        5        9  123456789         0         h
77        6        9  123456789         0         h
78        7        9  123456789         0         i
79        8        9  123456789         0         i
80        9        9  123456789         0         i

[81 rows x 5 columns]

## 3.0   更新棋盘信息

In [14]:
#更新num——list
def update_table():
    check_indexs=sudoku_df[sudoku_df['num_real']!=0].index
    print('start to check if there has num_real to update')
    #检查每一个确定了数字的格子blog
    for index_num in check_indexs:
        
        num=sudoku_df.loc[index_num,'num_real']
        update_associated_blog(index_num,num)

In [15]:
update_table()

start to check if there has num_real to update
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18, 19, 20, 29, 38, 47, 56, 65, 74]
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 14, 21, 22, 23, 30, 39, 48, 57, 66, 75]
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 14, 21, 22, 23, 32, 41, 50, 59, 68, 77]
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17, 24, 25, 26, 33, 42, 51, 60, 69, 78]
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 27, 36, 45, 54, 63, 72]
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 28, 37, 46, 55, 64, 73]
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 32, 41, 50, 59, 68, 77]
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 24, 25, 26, 35, 44, 53, 62, 71, 80]
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 37, 46, 55, 64, 73]
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[3, 4, 5, 12, 13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 30, 39, 48, 57, 66, 75]
pass
----------
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
pass
----------
后续将更新blog的index为：
[3, 4, 5, 12, 13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 31, 40, 49, 58, 67, 76]
pass
----------
----------
pass
----------
----------
----------
pass
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[6, 7, 8, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 33, 42, 51, 60, 69, 78]
pass
----------
----------
----------
----------
----------
pass
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
后续将更新blog的index为：
[1, 10, 19, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 45, 46, 47, 55, 64, 73]
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
后续将更新blog的index为：
[2, 11, 20, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 45, 46, 47, 56, 65, 74]
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
后续将更新blog的index为：
[7, 16, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 42, 43, 44, 51, 52, 53, 61, 70, 79]
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[8, 17, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 42, 43, 44, 51, 52, 53, 62, 71, 80]
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
后续将更新blog的index为：
[2, 11, 20, 27, 28, 29, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 56, 65, 74]
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 9, 18, 27, 28, 29, 36, 37, 38, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 63, 72]
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
后续将更新blog的index为：
[1, 10, 19, 27, 28, 29, 36, 37, 38, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 64, 73]
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[5, 14, 23, 30, 31, 32, 39, 40, 41, 45, 46, 47, 48, 49, 50, 51, 52, 53, 59, 68, 77]
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[6, 15, 24, 33, 34, 35, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 60, 69, 78]
pass
----------
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
后续将更新blog的index为：
[6, 15, 24, 33, 42, 51, 54, 55, 56, 57, 58, 59, 60, 61, 62, 69, 70, 71, 78, 79, 80]
pass
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[8, 17, 26, 35, 44, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 69, 70, 71, 78, 79, 80]
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 9, 18, 27, 36, 45, 54, 55, 56, 63, 64, 65, 72, 73, 74, 75, 76, 77, 78, 79, 80]
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[3, 12, 21, 30, 39, 48, 57, 58, 59, 66, 67, 68, 72, 73, 74, 75, 76, 77, 78, 79, 80]
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------

In [16]:
# 更新已经确定了的blog
def re_check():
    index_change=sudoku_df[(sudoku_df['num_list'].str.len()==1)&(sudoku_df['num_real']==0)].index
    while len(index_change)>0 :    
        for index_num in index_change:
            num=int(sudoku_df.loc[index_num,'num_list'])
            sudoku_df.loc[index_num,'num_real']=num
            update_associated_blog(index_num,num)
        index_change=sudoku_df[(sudoku_df['num_list'].str.len()==1)&(sudoku_df['num_real']==0)].index

In [17]:
re_check()

后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 45, 54, 63, 72]
----------
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
pass
----------
----------
----------
pass
----------
后续将更新blog的index为：
[2, 11, 20, 27, 28, 29, 36, 37, 38, 45, 46, 47, 48, 49, 50, 51, 52, 53, 56, 65, 74]
pass
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 9, 18, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 45, 46, 47, 54, 63, 72]
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
后续将更新blog的index为：
[0, 9, 18, 27, 28, 29, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 54, 63, 72]
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18, 19, 20, 27, 36, 45, 54, 63, 72]
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
后续将更新blog的index为：
[1, 10, 19, 27, 28, 29, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 55, 64, 73]
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 14, 21, 22, 23, 31, 40, 49, 58, 67, 76]
pass
----------
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18, 19, 20, 28, 37, 46, 55, 64, 73]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 30, 39, 48, 57, 66, 75]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
pass
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17, 24, 25, 26, 35, 44, 53, 62, 71, 80]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
----------
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
pass
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 29, 38, 47, 56, 65, 74]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 31, 40, 49, 58, 67, 76]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17, 24, 25, 26, 34, 43, 52, 61, 70, 79]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 24, 25, 26, 34, 43, 52, 61, 70, 79]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
----------
----------
后续将更新blog的index为：
[0, 1, 2, 9, 10, 11, 18, 19, 20, 21, 22, 23, 24, 25, 26, 29, 38, 47, 56, 65, 74]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
后续将更新blog的index为：
[3, 4, 5, 12, 13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 32, 41, 50, 59, 68, 77]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
----------
----------
----------
后续将更新blog的index为：
[2, 11, 20, 29, 38, 47, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 72, 73, 74]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
pass
----------
----------
----------
----------
pass
----------
----------
pass
----------
----------
----------
----------
pass
----------
----------
----------
后续将更新blog的index为：
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 24, 25, 26, 33, 42, 51, 60, 69, 78]
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
pass
----------
----------
----------
----------
----------
pass
----------
pass
----------
----------
----------

In [18]:
# 生成棋盘求解视图
def show_table(sudoku_df):
    mid_table=pd.pivot(sudoku_df,values='num_list',index=['row_num','group_key'],columns=['col_num'])
    return mid_table.fillna('')

In [19]:
show_table(sudoku_df)

col_num            1  2   3    4      5    6     7       8      9
row_num group_key
1       a          1  8   2
        d                      4      5    7
        g                                       39      39      6
2       a          5  3   9
        d                      2      6    8
        g                                      147     147     17
3       a          4  7   6
        d                      1      3    9
        g                                        5      28     28
4       b          9  1   5
        e                    678    278   23
        h                                      367   23678      4
5       b          7  4   3
        e                    689   1289   12
        h                                      169  125689  12589
6       b          6  2   8
        e                     79   1479    5
        h                                     1379    1379   1379
7       c          8  5   1
        f                     79    479    6
        i                                        2    3479    379
8       c          3  9  47
        f                      5  12478  124
        i                                     1467    1467     17
9       c          2  6  47
        f                      3   1479   14
        i                                        8   14579   1579

## 4.0 找到互斥的twin——df

In [20]:
# 将twins——df 相关blog 的num——list 进行更新
def pop_num_list_realateto_twins_df(col_name,num_list,unit_no):
    
    # 找到同一row/col/group 的 index，排除掉 twin——df 自己
    to_check_index=sudoku_df[(sudoku_df[col_name]==unit_no)&(sudoku_df['num_list']!=num_list)].index    
    sudoku_df.loc[to_check_index,'num_list']=(sudoku_df.loc[to_check_index,'num_list']).str.replace(num_list[0],'')
    sudoku_df.loc[to_check_index,'num_list']=(sudoku_df.loc[to_check_index,'num_list']).str.replace(num_list[1],'')

In [21]:
def find_the_same_unit(the_df,num_list):
    
    
    
    #判断是否有相同的row——num
    if the_df[pd.DataFrame.duplicated(the_df,subset=['row_num'])].empty:
        print('no find same row_num')
    else:
        #找到row_num 相同的
        the_df=the_df[pd.DataFrame.duplicated(the_df,subset=['row_num'],keep=False)]
        unit_no=the_df['row_num'].iloc[0]
        col_name='row_num'
        pop_num_list_realateto_twins_df(col_name,num_list,unit_no)
        
     #判断是否有相同的col——num
    if the_df[pd.DataFrame.duplicated(the_df,subset=['col_num'])].empty:
        print('no find same col_num')
    else:
        #找到row_num 相同的
        the_df=the_df[pd.DataFrame.duplicated(the_df,subset=['col_num'],keep=False)]
        unit_no=the_df['col_num'].iloc[0]
        
        col_name='col_num'
        pop_num_list_realateto_twins_df(col_name,num_list,unit_no)
    
    #判断是否有相同的group_key
    if the_df[pd.DataFrame.duplicated(the_df,subset=['group_key'])].empty:
        print('no find same group')
    else:
        #找到group——key 相同的
        the_df=the_df[pd.DataFrame.duplicated(the_df,subset=['group_key'],keep=False)]
        unit_no=the_df['group_key'].iloc[0]
        col_name='group_key'
        pop_num_list_realateto_twins_df(col_name,num_list,unit_no)

In [22]:
def recheck_twins_df():
    # 找到num——list 只有两种可能性的df
    two_num_df=sudoku_df[sudoku_df['num_list'].str.len()==2]
    #找到成对出现的twins_df(也可能有3个)
    count_df=two_num_df.groupby('num_list').count()
    twin_df_numlist=count_df[count_df['row_num']>1].index

    # 查询成对出现的df 是否有相同的 row/col/group
    for num_list in twin_df_numlist:
        the_df=two_num_df[two_num_df['num_list']==num_list]
        print(the_df)
        find_the_same_unit(the_df,num_list)

In [23]:

recheck_twins_df()

    row_num  col_num num_list  num_real group_key
73        2        9       17         0         g
79        8        9       17         0         i
no find same row_num
no find same group
    row_num  col_num num_list  num_real group_key
65        3        8       28         0         g
74        3        9       28         0         g
no find same col_num
    row_num  col_num num_list  num_real group_key
54        1        7       39         0         g
63        1        8       39         0         g
no find same col_num
    row_num  col_num num_list  num_real group_key
25        8        3       47         0         c
26        9        3       47         0         c
no find same row_num
    row_num  col_num num_list  num_real group_key
32        6        4       79         0         e
33        7        4       79         0         f
no find same row_num
no find same group

In [24]:
show_table(sudoku_df)

col_num            1  2   3   4      5    6     7       8     9
row_num group_key
1       a          1  8   2
        d                     4      5    7
        g                                      39      39     6
2       a          5  3   9
        d                     2      6    8
        g                                     147     147    17
3       a          4  7   6
        d                     1      3    9
        g                                       5      28    28
4       b          9  1   5
        e                    68    278   23
        h                                     367   23678     4
5       b          7  4   3
        e                    68   1289   12
        h                                     169  125689  2589
6       b          6  2   8
        e                    79   1479    5
        h                                    1379    1379    39
7       c          8  5   1
        f                    79    479    6
        i                                       2    3479    39
8       c          3  9  47
        f                     5  12478  124
        i                                    1467    1467    17
9       c          2  6  47
        f                     3   1479   14
        i                                       8   14579    59

In [25]:
sudoku_df['col_num'][0]

1